nohup: ignoring input
torch.Size([14031, 5, 64, 32])
torch.Size([4677, 5, 64, 32])
torch.Size([4678, 5, 64, 32])
Shape: (5, 144, 72)
Fine Tuning Both
Starting Latent Downstream Task
4
Epoch: 1, Train Loss: 0.2760, Valid Loss: 0.3249, LR: 0.01
/usr/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 78 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-uzfvc0q9': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-wi24fzda': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-mb9936qg': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-q89b7wsc': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-x33vf3i4': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-uebajs_d': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-pb5xtv39': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-e7uylg3a': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-ur7jsin7': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-jv3fwxav': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-f5sip69i': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-yotal2ce': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-j31dzwb2': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-4k29rpdy': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-ae03di6f': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-yemyebo2': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-z0sg5af8': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-_m5tldu1': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-wzrbvzw7': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-dynzmcpe': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-tr9nshlr': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-shv1jtqi': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-i08fn_6a': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-a3p_4mjo': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-fbcfonro': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-w3vxom6j': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-0ngn08o3': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-50q4fpmk': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-mql8x7oj': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-0ist85ms': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-59mg6ypw': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-y78_zikv': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-_dj4kxon': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-rftq2c4d': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-f8ee6fql': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-jdh8eox0': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-dam9r0eh': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-r87ymlbp': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-4a0e4zvn': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-e0pd00qq': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-k4fv7ryp': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-plrl01h3': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-n0t1eb_8': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-_xuenycz': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-szamg24j': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-njpsz7iq': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-6diydcez': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-tynql__z': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-5mxah85o': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-qf2zsgs3': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-13eu8rxz': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-kls5sehr': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-3a6dxpdw': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-q91o980v': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-wpj8zxc4': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-_yn11afe': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-xfyswtif': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-1_ts6mbc': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-3bmlzahj': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-1ltjhd60': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-9d8ua9mn': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-lx_frfau': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-mrkifszx': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-zxg9z6y0': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-4gqwbp7c': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-bre8ajjc': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-ppzbcouu': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-qokcaclw': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-1jav2_y9': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-vsder1d1': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-3msw297s': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-i1uop5ri': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-vvb9ix_0': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-munnmfwf': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-ukdksa1j': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-1vldogql': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-n918_346': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/mp-d455zt__': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
